CONF_ENTRY(CString,InitialKey,"RELAY_INITIAL_KEY","EIBKEY")
CONF_ENTRY(bool, AutoDiscoverEibServer,"AUTO_DISCOVER_EIB_SERVER", true)
CONF_ENTRY(CString,EibIPAddress,"EIB_SERVER_IP_ADDRESS","127.0.0.1")
CONF_ENTRY(int,EibPort,"EIB_SERVER_PORT",5000)
CONF_ENTRY(CString,Name,"RELAY_SERVER_NAME","RELAY")
CONF_ENTRY(CString,NetworkName,"RELAY_NETWORK_NAME","RELAY")
CONF_ENTRY(CString,Password,"RELAY_SERVER_PASSWORD","RELAY")
CONF_ENTRY(int,LogLevel,"LOG_LEVEL",3)
#ifdef WIN32
CONF_ENTRY(int,ListenInterface,"LISTEN_INTERFACE",1)
#else
CONF_ENTRY(CString,ListenInterface,"LISTEN_INTERFACE","eth0")
#endif
