CONF_ENTRY(CString,InitialKey,"SMS_INITIAL_KEY","EIBKEY")
CONF_ENTRY(bool, AutoDiscoverEibServer,"AUTO_DISCOVER_EIB_SERVER", true)
CONF_ENTRY(CString,EibIPAddress,"EIB_SERVER_IP_ADDRESS","127.0.0.1")
CONF_ENTRY(int,EibPort,"EIB_SERVER_PORT",5000)
CONF_ENTRY(CString,Name,"SMS_SERVER_NAME","SMS")
CONF_ENTRY(CString,NetworkName,"SMS_NETWORK_NAME","SMS")
CONF_ENTRY(CString,Password,"SMS_SERVER_PASSWORD","SMS")
CONF_ENTRY(int,DeviceBaudRate,"SMS_DEVICE_BAUD_RATE",19200)
#ifdef WIN32
CONF_ENTRY(int,ListenInterface,"LISTEN_INTERFACE",1)
CONF_ENTRY(CString,Device,"SMS_DEVICE","COM1")
#else
CONF_ENTRY(CString,ListenInterface,"LISTEN_INTERFACE","eth0")
CONF_ENTRY(CString,Device,"SMS_DEVICE","/dev/ttyUSB0")
#endif
